#voornaam = input('Wat is je voornaam?')
achternaam = input('Wat is je achternaam?')
print('Halo', voornaam, achternaam)
naam = input('Wat is jouw naam')
straat = input('In welke straat woon je?')
huisnummer = input('Wat is jouw huis nummer?')
postcode = input('Wat is jouw postcode')
woonplaats = input('Wat is jouw woonplaats')
print(naam)
print(straat, huisnummer)
print(postcode.upper(), woonplaats.upper())
